name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: 1999498
          owner: 'veeru13055'
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.13
        with:
          token: '${{ steps.get_token.outputs.token }}'
          configurationFile: example/renovate-config.js
