name: test
on:
  workflow_dispatch:
jobs:
  print-token:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Token
        run: |
          TOKEN=${{ secrets.MY_TOKEN }}
          echo "Actual token: $TOKEN"

